{
 "title": "Imua Dashboard by Cumulo Copy",
 "description": "This dashboard provides a comprehensive overview of the health and performance of a Imua blockchain node. It monitors sync status, consensus metrics, block processing times, transaction activity, validator participation, and system resource usage. The dashboard helps identify network issues, node performance bottlenecks, and memory management efficiency, offering critical insights for maintaining an optimized and healthy node.\nFor detailed documentation of the metrics, visit:\nhttps://github.com/Cumulo-pro/ExocoreTools/blob/main/monitoring/exocore_metrics.md#block-interval-time-sum",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align: center;\">\n    <p><img src=\"https://cumulo.pro/images/imua.png\" alt=\"Logo\" style=\"height: 55px;\"> <!-- Ajusta la altura según sea necesario -->\n    </p>\n    <h2>Imua  Node metrics</h2>\n    <h5>by <a href=\"https://cumulo.pro\">Cumulo</a></h5>\n    <p><a href=\"https://github.com/Cumulo-pro/ExocoreTools/blob/main/monitoring/exocore_metrics.md#block-interval-time-sum\">Imua  Node Metrics Documentation</a>\n</div>"
   }
  },
  {
   "title": "Sync Status ",
   "type": "stat",
   "description": "Indicates whether the node is currently syncing blocks. Displays 1 if syncing, 0 if not. Helps diagnose the synchronization status, allowing operators to confirm if the node is up-to-date",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_syncing{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain Height",
   "type": "stat",
   "description": "Displays the current height of the chain. Useful for confirming node progress and ensuring it is in sync with the network.",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_height{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Validators",
   "type": "gauge",
   "description": "Represents the total number of validators in the network. Useful for monitoring the size of the validator set.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validators{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Syncing Status",
   "type": "stat",
   "description": "Indicates if the node is currently state syncing. Displays 1 if syncing, 0 if not. Helps diagnose the state sync status, allowing operators to confirm if the node is up-to-date",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_state_syncing{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Peers",
   "type": "gauge",
   "description": "Displays the number of peers connected to the node. Important for understanding the node’s connectivity and resilience in the network.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_p2p_peers{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed Blocks (Validator)",
   "type": "stat",
   "description": "Indicates the number of blocks missed by the validator.Helps monitor validator reliability and can signal issues with validator performance.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_missed_blocks{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Power",
   "type": "timeseries",
   "description": "Shows the voting power of a specific validator. Provides insights into the influence of a validator within the network, based on its assigned voting power.",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_power{job=\"$job\"}",
     "legendFormat": "validator address:{{validator_address}}"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "stat",
   "description": "Measures the size of the most recent block in bytes. Provides insights into block capacity usage, which can be useful for understanding the volume of data processed per block.",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_block_size_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Signed Height (Validator)",
   "type": "stat",
   "description": "Displays the last block height signed by the validator.Useful for tracking validator activity and confirming timely participation.",
   "gridPos": { "h": 10, "w": 7, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_validator_last_signed_height{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nº Missing Validators",
   "type": "timeseries",
   "description": "This metric shows the voting power (stake) that absent validators represent. A high power of absent validators can have a negative impact on the security and decentralization of the network, as it reduces the available consensus power. Value: total power of the validators who are absent in the consensus process.",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{job=\"$job\"}",
     "legendFormat": "voting power (stake) that absent validators"
    }
   ]
  },
  {
   "title": "Number of Transactions ",
   "type": "stat",
   "description": "Displays the number of transactions included in the current block. Offers insight into network activity and transaction throughput.",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_num_txs{job=\"$job\"}",
     "legendFormat": "Txs"
    }
   ]
  },
  {
   "title": "Total Transactions ",
   "type": "timeseries",
   "description": "Shows the total number of transactions processed by the node.Offers an overview of the transaction throughput, indicating network activity levels.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "cometbft_consensus_total_txs{job=\"$job\"}",
     "legendFormat": "Txs"
    }
   ]
  },
  {
   "title": "State Block  Processing Time",
   "type": "histogram",
   "description": "This histogram metric measures the time taken between the BeginBlock and EndBlock events in milliseconds, with various time intervals. Helps monitor the block processing duration, which is essential for understanding the efficiency of block execution and identifying potential bottlenecks.",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "cometbft_state_block_processing_time_bucket{job=\"$job\"}",
     "legendFormat": "le: {{le}}"
    }
   ]
  },
  {
   "title": "Average Block Processing Time",
   "type": "timeseries",
   "description": "This metric provides the average time it takes for the node to process a block, calculated by dividing the total block processing time (cometbft_state_block_processing_time_sum) by the total number of blocks processed (cometbft_state_block_processing_time_count). Monitoring the average block processing time is crucial for evaluating the efficiency of block finalization. If the average time increases, it may indicate potential performance bottlenecks or issues with the node's processing power. Keeping the average block processing time within an optimal range helps ensure the smooth functioning of the network and avoids delays in transaction finalization.",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_state_block_processing_time_sum{job=\"$job\"}",
     "legendFormat": "Block Processing Time Sum "
    },
    {
     "expr": "cometbft_state_block_processing_time_count{job=\"$job\"}",
     "legendFormat": "Block Processing Time Count"
    },
    { "expression": "$A/$B", "type": "math" }
   ]
  },
  {
   "title": "Late Votes",
   "type": "timeseries",
   "description": "Shows the count of votes received by the node that correspond to earlier heights and rounds than the current state, categorized by vote type (prevote or precommit). Allows monitoring of late votes, which can help diagnose potential network latency or communication issues.",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "cometbft_consensus_late_votes{job=\"$job\"}",
     "legendFormat": "Vote Type: {{vote_type}}"
    }
   ]
  },
  {
   "title": "Proposal Receive Count",
   "type": "timeseries",
   "description": "Shows the count of proposals received by the node since its start, categorized by status (accepted or rejected). Useful for tracking proposal processing rates and success rates of proposals.",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cometbft_consensus_proposal_receive_count{job=\"$job\"}",
     "legendFormat": "Status: {{status}}"
    }
   ]
  },
  { "title": "Validator data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Nº Missing Validators ",
   "type": "gauge",
   "description": "Represents the number of validators that failed to sign the latest block. Aids in identifying validator participation and availability issues.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missing Validators Power",
   "type": "stat",
   "description": "Shows the total power of validators that did not sign the latest block. Highlights the influence of missing validators on network consensus based on their voting power.",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_consensus_missing_validators_power{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Parameter Updates",
   "type": "stat",
   "description": "Counts the total number of times consensus parameters have been updated since the process started. Useful for tracking changes in consensus configuration, which may affect network operation and performance.",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_state_consensus_param_updates{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Byzantine Validators Power ",
   "type": "timeseries",
   "description": "Displays the total power of validators involved in byzantine behavior. Highlights the impact of byzantine validators based on their total voting power.",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 41 },
   "targets": [
    {
     "expr": "cometbft_consensus_byzantine_validators_power{job=\"$job\"}",
     "legendFormat": "total power of byzantine validators"
    }
   ]
  },
  {
   "title": "Byzantine Validators ",
   "type": "timeseries",
   "description": "Shows the count of validators that attempted to double-sign or engage in other byzantine behavior.Aids in identifying malicious validators in the network.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 41 },
   "targets": [
    {
     "expr": "cometbft_consensus_byzantine_validators{job=\"$job\"}",
     "legendFormat": "Nº validators that attempted to double-sign"
    }
   ]
  },
  {
   "title": "Total Validators Power",
   "type": "timeseries",
   "description": "Indicates the cumulative voting power of all validators. Helps gauge the overall security and decentralization of the network.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "cometbft_consensus_validators_power{job=\"$job\"}",
     "legendFormat": "Chain-Id{{chain_id}}"
    }
   ]
  },
  {
   "title": "Full Prevote Delay",
   "type": "timeseries",
   "description": "Measures the time interval between the proposal timestamp and the timestamp of the latest prevote in a round where all validators have voted, segmented by proposer_address. Helps track and optimize the consensus round timing.",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 48 },
   "targets": [
    {
     "expr": "cometbft_consensus_full_prevote_delay{job=\"$job\"}",
     "legendFormat": "proposer: {{proposer_address}}"
    }
   ]
  },
  { "title": "Block info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Block Interval Average",
   "type": "timeseries",
   "description": "This metric calculates the average block interval time on the cometbft blockchain, enabling monitoring of block production consistency and detecting potential delays. The average is derived by dividing the total interval time (cometbft_consensus_block_interval_seconds_sum) by the block count (cometbft_consensus_block_interval_seconds_count) over a specified time range. This provides insight into the block production speed over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "rate(cometbft_consensus_block_interval_seconds_sum{job=\"$job\"}[5m]) / rate(cometbft_consensus_block_interval_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Interval Time Count",
   "type": "timeseries",
   "description": "Indicates the total number of recorded block intervals. Useful for verifying the regularity of block production and ensuring the node consistently registers blocks.\nEssential for calculating the average block interval and checking production frequency.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_count{job=\"$job\"}",
     "legendFormat": "number of recorded block intervals"
    }
   ]
  },
  {
   "title": "Block Interval Time Sum",
   "type": "timeseries",
   "description": "Represents the cumulative time elapsed between blocks since monitoring started. Useful for calculating the average time between blocks when combined with count.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_interval_seconds_sum{job=\"$job\"}",
     "legendFormat": "cumulative time elapsed "
    }
   ]
  },
  {
   "title": "Block Parts Transmitted by Peer",
   "type": "timeseries",
   "description": "Shows the number of block parts sent by each peer in the network, identified by peer_id. Allows monitoring the distribution of block parts, which can help identify network traffic patterns or potential issues in data sharing between peers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "cometbft_consensus_block_parts{job=\"$job\"}",
     "legendFormat": "peer: {{peer_id}}"
    }
   ]
  },
  { "title": "Mempool & P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Mempool Size",
   "type": "gauge",
   "description": "Shows the number of uncommitted transactions in the mempool. Useful for understanding transaction backlog and network congestion.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Message Received Bytes",
   "type": "barchart",
   "description": "Counts the number of bytes received for each P2P message type (e.g., blocksync_BlockResponse, consensus_BlockPart). Enables analysis of network traffic and data flow efficiency, helping to optimize P2P performance.",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 75 },
   "targets": [
    {
     "expr": "cometbft_p2p_message_receive_bytes_total{job=\"$job\"}",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Mempool Size in Bytes ",
   "type": "gauge",
   "description": "Indicates the total size of transactions in the mempool, in bytes. Helps assess memory usage and transaction volume awaiting processing.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_size_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Outbound Connections in Mempool",
   "type": "gauge",
   "description": "Shows the number of connections actively used for gossiping transactions in the mempool. Helps monitor network connectivity and transaction dissemination efficiency.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 85 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_active_outbound_connections{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Message Sent Bytes",
   "type": "timeseries",
   "description": "Shows the number of bytes sent for each P2P message type. Helps in assessing outbound traffic and understanding message distribution patterns.",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 85 },
   "targets": [
    {
     "expr": "cometbft_p2p_message_send_bytes_total{job=\"$job\"}",
     "legendFormat": "message_type: {{message_type}}"
    }
   ]
  },
  {
   "title": "Mempool Recheck Count",
   "type": "gauge",
   "description": "Counts the number of times transactions are rechecked in the mempool. Provides insights into transaction re-evaluation processes, useful for analyzing mempool behavior.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cometbft_mempool_recheck_times{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Go Garbage Collection Duration",
   "type": "timeseries",
   "description": "This summary metric captures the duration of garbage collection cycles in seconds, with various quantiles. Helps assess the impact of garbage collection on performance, allowing for memory management optimization.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"$job\"}",
     "legendFormat": "quantile: {{quantile}}"
    }
   ]
  },
  {
   "title": "Number of Goroutines ",
   "type": "timeseries",
   "description": "Shows the current number of goroutines.Useful for monitoring concurrency in Go applications, as excessive goroutines may indicate resource contention or potential memory leaks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\"}",
     "legendFormat": "Nº goroutines in execution. "
    }
   ]
  },
  {
   "title": "Process CPU Seconds Total",
   "type": "stat",
   "description": "Total CPU time consumed by the process",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"$job\"}",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Process Resident Memory Bytes ",
   "type": "timeseries",
   "description": "Resident memory size in bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\"}",
     "legendFormat": "bytes"
    }
   ]
  }
 ]
}